# Generated by Django 4.1 on 2022-08-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_records_criminals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='criminal_name',
        ),
        migrations.AlterField(
            model_name='records',
            name='criminals',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyApp.criminals'),
            preserve_default=False,
        ),
    ]
